sudo: true
language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-7-jdk
services: docker
python:
- '3.6'
script:
 - ant 
 - ls dist/
