sudo: true
language: java
services: docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-7-jdk

script:
 - ant
 - docker build -t suvarchal/ramadda -f ci/deploy/dockerfile_ramadda
 - docker build -t suvarchal/ramadda-geoscience -f ci/deploy/dockerfile_ramadda-geoscience 
 - docker images

before_deploy:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
   provider: script
   script: docker push "suvarchal/ramadda:latest" && docker push "suvarchal/ramadda-geoscience:latest"
   on:
     branch: master 
